// Arrows: Maze Escape Puzzle Logic
// Based on the interlocking labyrinth escape mechanic

export const MAZE_LEVELS = [
  {
    id: 1,
    name: "VECTOR APERTURE",
    difficulty: "LEVEL 01",
    desc: "Tap the unblocked arrow to launch it. Clear the corridor for the Master Blue Arrow!",
    arrows: [
      // Each arrow has: id, label, dir ('UP','DOWN','LEFT','RIGHT'), color, isEscape (master arrow),
      // blockedBy: array of arrow ids that must leave first, path: 3D polyline points
      {
        id: 'A1',
        label: 'SCOUT-1',
        dir: 'UP',
        isEscape: false,
        color: '#1e3a8a',
        blockedBy: [], // Can escape right away!
        // Start pos [x, y], exit vector [vx, vy]
        start: [-1.2, 0.4],
        exitVector: [0, 4.0],
        pathPoints: [
          [-1.2, 0.4],
          [-1.2, 1.4],
        ],
      },
      {
        id: 'A2',
        label: 'BLOCKER-2',
        dir: 'RIGHT',
        isEscape: false,
        color: '#1e293b',
        blockedBy: ['A1'], // Blocked until A1 leaves
        start: [-1.2, -0.6],
        exitVector: [4.0, 0],
        pathPoints: [
          [-1.2, -0.6],
          [0.6, -0.6],
        ],
      },
      {
        id: 'MASTER',
        label: 'ESCAPE ARROW',
        dir: 'RIGHT',
        isEscape: true,
        color: '#00f3ff',
        blockedBy: ['A2'], // Escapes once A2 is gone!
        start: [-1.4, 0.0],
        exitVector: [4.5, 0],
        pathPoints: [
          [-1.4, 0.0],
          [-0.6, 0.0],
          [-0.6, -1.0],
          [0.2, -1.0],
          [0.2, 0.8],
          [1.0, 0.8],
          [1.0, 0.0],
          [1.8, 0.0],
        ],
      },
    ],
  },
  {
    id: 2,
    name: "INTERLOCKING CIRCUIT",
    difficulty: "LEVEL 02",
    desc: "Multiple cross-blocking arrows. Untangle the priority sequence.",
    arrows: [
      {
        id: 'B1',
        label: 'V-UP',
        dir: 'UP',
        isEscape: false,
        color: '#1e3a8a',
        blockedBy: [],
        start: [1.2, 0.2],
        exitVector: [0, 4.0],
        pathPoints: [
          [1.2, 0.2],
          [1.2, 1.6],
        ],
      },
      {
        id: 'B2',
        label: 'V-LEFT',
        dir: 'LEFT',
        isEscape: false,
        color: '#172554',
        blockedBy: [],
        start: [-0.2, -1.2],
        exitVector: [-4.0, 0],
        pathPoints: [
          [-0.2, -1.2],
          [-1.6, -1.2],
        ],
      },
      {
        id: 'B3',
        label: 'V-DOWN',
        dir: 'DOWN',
        isEscape: false,
        color: '#0f172a',
        blockedBy: ['B2'],
        start: [-0.6, 0.8],
        exitVector: [0, -4.0],
        pathPoints: [
          [-0.6, 0.8],
          [-0.6, -0.6],
        ],
      },
      {
        id: 'B4',
        label: 'V-RIGHT',
        dir: 'RIGHT',
        isEscape: false,
        color: '#1e293b',
        blockedBy: ['B1'],
        start: [0.2, 0.4],
        exitVector: [4.0, 0],
        pathPoints: [
          [0.2, 0.4],
          [1.4, 0.4],
        ],
      },
      {
        id: 'MASTER',
        label: 'ESCAPE VECTOR',
        dir: 'RIGHT',
        isEscape: true,
        color: '#00f3ff',
        blockedBy: ['B3', 'B4'],
        start: [-1.5, 0.1],
        exitVector: [4.5, 0],
        pathPoints: [
          [-1.5, 0.1],
          [-1.0, 0.1],
          [-1.0, 1.2],
          [0.0, 1.2],
          [0.0, -0.8],
          [0.8, -0.8],
          [0.8, 0.3],
          [1.8, 0.3],
        ],
      },
    ],
  },
  {
    id: 3,
    name: "THE GRAND LABYRINTH",
    difficulty: "LEVEL 03 // MASTER",
    desc: "The authentic labyrinth from the game. Sequence every vector to free the master arrow!",
    arrows: [
      {
        id: 'M1',
        label: 'TOP-NORTH',
        dir: 'UP',
        isEscape: false,
        color: '#172554',
        blockedBy: [],
        start: [-1.1, 0.6],
        exitVector: [0, 4.0],
        pathPoints: [[-1.1, 0.6], [-1.1, 1.5]],
      },
      {
        id: 'M2',
        label: 'UPPER-EAST',
        dir: 'RIGHT',
        isEscape: false,
        color: '#1e293b',
        blockedBy: ['M1'],
        start: [-0.8, 1.2],
        exitVector: [4.0, 0],
        pathPoints: [[-0.8, 1.2], [0.8, 1.2]],
      },
      {
        id: 'M3',
        label: 'BOTTOM-SOUTH',
        dir: 'DOWN',
        isEscape: false,
        color: '#0f172a',
        blockedBy: [],
        start: [0.3, -0.2],
        exitVector: [0, -4.0],
        pathPoints: [[0.3, -0.2], [0.3, -1.6]],
      },
      {
        id: 'M4',
        label: 'WEST-SCOUT',
        dir: 'LEFT',
        isEscape: false,
        color: '#1e3a8a',
        blockedBy: [],
        start: [-0.4, -0.8],
        exitVector: [-4.0, 0],
        pathPoints: [[-0.4, -0.8], [-1.5, -0.8]],
      },
      {
        id: 'M5',
        label: 'MID-NORTH',
        dir: 'UP',
        isEscape: false,
        color: '#1e293b',
        blockedBy: ['M3'],
        start: [0.8, -0.9],
        exitVector: [0, 4.0],
        pathPoints: [[0.8, -0.9], [0.8, 0.2]],
      },
      {
        id: 'M6',
        label: 'EAST-BLOCKER',
        dir: 'RIGHT',
        isEscape: false,
        color: '#172554',
        blockedBy: ['M5'],
        start: [0.6, -1.2],
        exitVector: [4.0, 0],
        pathPoints: [[0.6, -1.2], [1.6, -1.2]],
      },
      {
        id: 'MASTER',
        label: 'ESCAPE PROTOCOL',
        dir: 'RIGHT',
        isEscape: true,
        color: '#00f3ff',
        blockedBy: ['M2', 'M5', 'M6'],
        start: [-1.6, -0.2],
        exitVector: [4.5, 0],
        // The iconic winding path from the user's image!
        pathPoints: [
          [-1.6, -0.2],
          [-1.2, -0.2],
          [-1.2, -0.6],
          [-0.5, -0.6],
          [-0.5, 0.4],
          [0.6, 0.4],
          [0.6, -0.3],
          [1.1, -0.3],
          [1.1, 0.1],
          [1.8, 0.1],
        ],
      },
    ],
  },
];
